sudo: false
dist: trusty
language: node_js
node_js:
  - node

env:
  global:
    - secure: TsbZbKSgMVnz4lZYWG5WMbC1qHiI7jeTKg3HOxunzWdMNSbB5uWb+HGfPbt0co41dy8AIgBuK7IZ9PYA8E9P6oivD5h8HvVZOyKHIAXKnyqdRAcAtXTstEecDdKQ2OGAYRlpZ3Wj901xc8hkbPx5DdSGYN3Totmz/fx7PHoVgbtD/YHaxIXOZFAH6l3w7qiV5S/5C1Y+Lb5AzDKak3WaDlJLt+RjXe6lpDOKGvrmQFwpyYpxQrz/Fh9pDw54vVqhn57RByoVmhCM4rq0/Czf5BnK4sJDu0YuYmgRjqndkaO8XO/xOOsguK3G33gouW7IJMSp7++q5jMjnvVXTBzaiKEp7Qw9oE26NplaY9Nwxuj9o0gNMJJaFAfZn9/ZkXDKaYV0jezOf5zI5sLAPEStIotf8w+L8n13zqr469CYjoHI9WxpKOoy+MbJPOCC7N+5NXHRVW1LCWD/Yt9urlDD2S2JxblbC6xZd/FWhl3iMURoTxj6SK5J1dWBMOFwNCIM8ZjTBQtmzP49tRHoH0EDpgoaPpjrz4MPVPIuVuXbEMu0xB3oK5oCN3X+nie03z0BmsjYIm0XfAzCOB8VEk3SqMfzDoPfHI+5fW+rSaGjiK3A5g2naJTPJvWeQMCC3j32Sg4n/XSdfAwLb+vrJFZ3RhiEiCi0xsCjns0VEQCVm3E=
  matrix:
    - TYPE="unit"
    - TYPE="integration" ATOM_CHANNEL="stable"
    - TYPE="integration" ATOM_CHANNEL="beta"

cache:
  directories:
    - node_modules

branches:
  except:
    - gh-pages

notifications:
  email:
    on_success: change
    on_failure: always

before_install:
  - if [ "$TYPE" == "unit" ]; then npm install -g codecov greenkeeper-lockfile; fi

before_script:
  - if [ "$TYPE" == "unit" ]; then greenkeeper-lockfile-update; fi
  - if [ "$TYPE" == "integration" ]; then
      npm run build;
      cd spec/integration;
      curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh;
      chmod u+x build-package.sh;
      fi

script:
  - if [ "$TYPE" == "unit" ]; then npm run lintdir -- src; fi
  - if [ "$TYPE" == "unit" ]; then npm run lintdir -- spec; fi
  - if [ "$TYPE" == "unit" ]; then (for dir in examples/*; do if [ -d "${dir}" ]; then cd "${dir}"; npm install; npm run lint; if [ $? -ne 0 ]; then exit 1; fi; cd ..; fi; done); fi
  - if [ "$TYPE" == "unit" ]; then npm run coverage; fi
  - if [ "$TYPE" == "integration" ]; then ./build-package.sh; fi

after_script:
  - if [ "$TYPE" == "unit" ]; then codecov; greenkeeper-lockfile-upload; fi
